"""Hand-written technical and commercial questions, grouped by route.

Each entry: (topic, difficulty 1-3, question, [4 options], correct index, plain-English explainer).
The explainer is what the student sees on reveal: short, simple, no jargon left unexplained.
"""

CONCEPTS = {
# --------------------------------------------------------------------------------------------
"accounting_audit": [
("Double entry", 1, "A company buys £5,000 of stock on credit. Which entry is correct?",
 ["Debit inventory £5,000, credit payables £5,000", "Debit payables £5,000, credit inventory £5,000",
  "Debit inventory £5,000, credit cash £5,000", "Debit cost of sales £5,000, credit cash £5,000"], 0,
 "Every transaction has two sides. The company gains an asset (stock, a debit) and owes the supplier (a payable, a credit). No cash moves yet because it bought on credit."),
("Accruals", 1, "Electricity used in December is billed in January. Under accruals accounting, when is the cost recognised?",
 ["December", "January", "When the bill is paid", "Split equally across both months"], 0,
 "Accruals means costs are recorded when they are incurred, not when cash leaves. The electricity was used in December, so it's a December cost, recorded as an accrual (a liability) until paid."),
("Prepayments", 1, "In March a company pays £12,000 for a year's insurance starting 1 April. At 31 March, how is it shown?",
 ["£12,000 prepayment (asset)", "£12,000 expense", "£1,000 expense and £11,000 prepayment", "£12,000 accrual (liability)"], 0,
 "None of the cover has been used yet, so the whole payment is an asset: a prepayment. It becomes an expense month by month as the cover is used."),
("Going concern", 2, "What does the going concern assumption mean?",
 ["The business will keep operating for the foreseeable future", "The business is profitable this year",
  "Assets are valued at what they would sell for today", "The business has more cash than debt"], 0,
 "Accounts assume the company will carry on trading for at least 12 months from the date the accounts are approved. If there's significant doubt, directors must disclose it and the auditor reports a material uncertainty related to going concern. If the business clearly can't continue, assets are valued on a break-up basis."),
("Audit opinion", 2, "An auditor issues an unmodified (clean) opinion. What does that mean?",
 ["The accounts give a true and fair view in all material respects", "The auditor checked every transaction",
  "The company has no fraud", "The company is financially healthy"], 0,
 "A clean opinion means the auditor has obtained reasonable assurance that the accounts are free from material misstatement and give a true and fair view. It does not mean every transaction was checked, that there's no fraud anywhere, or that the business is in good shape."),
("Materiality", 2, "In an audit, what is materiality?",
 ["The size of error that could change a reader's decisions", "The value of the company's physical assets",
  "Any error above £1,000", "The total of all errors found"], 0,
 "Materiality is the threshold where a misstatement would matter to someone relying on the accounts. Auditors often start from a percentage of profit or revenue, then use judgement."),
("Audit evidence", 2, "Which is usually the most reliable audit evidence?",
 ["A bank confirmation sent directly to the auditor", "A verbal explanation from the finance director",
  "A photocopy of an invoice supplied by the client", "An internal spreadsheet prepared by the client"], 0,
 "Evidence from an independent third party, received directly by the auditor, is hardest to manipulate. Evidence created or handled by the client is weaker."),
("Depreciation", 1, "Why do companies depreciate fixed assets?",
 ["To spread the asset's cost over the years it is used", "To build up cash to replace the asset",
  "To show the asset's market value", "To reduce the tax rate"], 0,
 "Depreciation matches the cost of an asset to the periods that benefit from it. It is not a cash fund and it doesn't track market value."),
("Revenue recognition", 2, "A software firm sells a 12-month subscription starting 1 January for £1,200, paid upfront. How much revenue is recognised in January?",
 ["£100", "£1,200", "£0", "£600"], 0,
 "Revenue is recognised as the service is delivered. One month of twelve has been delivered, so £100. The other £1,100 sits as deferred income (a liability)."),
("Deferred income", 2, "Deferred income appears on the balance sheet as:",
 ["A liability", "An asset", "Equity", "Revenue"], 0,
 "The company has been paid but still owes the customer a service. Until it's delivered, that obligation is a liability."),
("Inventory valuation", 2, "Inventory is valued at:",
 ["The lower of cost and net realisable value", "Its selling price", "The higher of cost and net realisable value", "Replacement cost"], 0,
 "Stock is held at cost unless it can only be sold for less (net realisable value), in which case it's written down. This stops profit being overstated."),
("Cash vs profit", 2, "A company is profitable but runs out of cash. Which is the most likely reason?",
 ["Customers are slow to pay and stock is building up", "Depreciation is too high",
  "It has too much equity", "Its gross margin is too high"], 0,
 "Profit includes sales made on credit. If customers don't pay and cash is tied up in stock, the business can be profitable on paper and still unable to pay its bills."),
("Working capital", 2, "Which change releases cash from working capital?",
 ["Collecting receivables faster", "Holding more inventory", "Paying suppliers sooner", "Offering customers longer credit terms"], 0,
 "Getting paid sooner turns receivables into cash. Holding more stock, paying suppliers early or giving customers longer to pay all tie cash up."),
("Three statements", 2, "Depreciation rises by £10m. Ignoring tax, what happens to operating cash flow?",
 ["No change", "Falls by £10m", "Rises by £10m", "Falls by £5m"], 0,
 "Depreciation reduces profit but isn't a cash payment. In the cash flow statement it's added back, so operating cash flow is unchanged (before tax effects)."),
("Three statements", 3, "Depreciation rises by £10m and the tax rate is 25%. What happens to operating cash flow?",
 ["Rises by £2.5m", "Falls by £10m", "No change", "Falls by £7.5m"], 0,
 "Pre-tax profit falls £10m, so tax falls £2.5m and net income falls £7.5m. Adding back the £10m depreciation leaves operating cash flow £2.5m higher: the tax saving."),
("Provisions", 3, "When should a company recognise a provision?",
 ["When there is a present obligation from a past event, an outflow is probable and it can be estimated reliably",
  "Whenever management expects a bad year", "Only when a court has ruled against it", "When cash has already been paid"], 0,
 "A provision needs all three: an obligation now because of something that already happened, a likely payment, and a reliable estimate. Otherwise it may only be disclosed."),
("Goodwill", 2, "Goodwill arises when:",
 ["A company pays more than the fair value of the net assets it acquires", "A company builds a strong brand internally",
  "A company sells assets above book value", "Customers recommend the company"], 0,
 "Goodwill is the premium paid in an acquisition above the fair value of identifiable net assets. Internally built brands are not recognised as goodwill."),
("Impairment", 2, "An asset is impaired when:",
 ["Its carrying amount is higher than its recoverable amount", "It is fully depreciated",
  "Its market value rises", "It is used more than expected"], 0,
 "If the business can no longer recover an asset's book value, through use or sale, it's written down to the recoverable amount and the loss hits profit."),
("Ratios", 1, "The current ratio is:",
 ["Current assets ÷ current liabilities", "Current liabilities ÷ current assets", "Cash ÷ total liabilities", "Net profit ÷ revenue"], 0,
 "It measures whether short-term assets cover short-term bills. Above 1 means current assets exceed current liabilities."),
("Ratios", 2, "Why is the quick ratio stricter than the current ratio?",
 ["It excludes inventory", "It includes long-term debt", "It uses profit instead of assets", "It excludes cash"], 0,
 "Stock can take time to sell, so the quick (acid-test) ratio leaves it out and asks whether liquid assets alone cover current liabilities."),
("Gross margin vs markup", 2, "A product costs £60 and sells for £100. Which is true?",
 ["Gross margin 40%, markup 67%", "Gross margin 67%, markup 40%", "Both are 40%", "Both are 67%"], 0,
 "Margin uses the selling price as the base (40 ÷ 100). Markup uses cost as the base (40 ÷ 60). Same £40 profit, different percentages."),
("Audit risk", 3, "Audit risk is made up of:",
 ["Inherent risk, control risk and detection risk", "Market risk, credit risk and liquidity risk",
  "Fraud risk, tax risk and legal risk", "Sampling risk only"], 0,
 "Inherent risk is how error-prone an area is. Control risk is whether the client's controls miss it. Detection risk is whether the auditor's own tests miss it. Auditors lower detection risk when the other two are high."),
("Controls", 2, "Which is a segregation of duties control?",
 ["The person who approves payments cannot also set up new suppliers", "All payments over £10,000 are reviewed monthly",
  "Passwords are changed every 90 days", "Invoices are filed by date"], 0,
 "Splitting key steps between different people stops one person from both creating and approving a fake transaction."),
("Professional scepticism", 2, "Professional scepticism means an auditor should:",
 ["Keep a questioning mind and critically assess evidence", "Assume management is dishonest",
  "Accept management's explanations if they are reasonable", "Test every transaction"], 0,
 "Scepticism isn't distrust. It means not accepting things at face value and looking for evidence that confirms or contradicts what you're told."),
("Commercial awareness", 2, "Interest rates rise sharply. Which client is most likely to show going concern risk?",
 ["A highly indebted retailer with floating-rate loans", "A cash-rich software company",
  "A pension fund with no borrowings", "A debt-free consultancy"], 0,
 "Floating-rate debt means interest costs rise immediately. A retailer with thin margins and heavy borrowing may struggle to cover them."),
("Commercial awareness", 2, "Why might an audit firm treat a fast-growing start-up client as higher risk?",
 ["Controls often lag growth and revenue may be recognised aggressively", "Start-ups never have auditors",
  "Growth always means fraud", "Start-ups pay lower fees"], 0,
 "Rapid growth stretches systems and people. Weak controls and pressure to show growth raise the chance of errors in areas like revenue."),
("Tax basics", 1, "VAT charged to customers is:",
 ["Collected on behalf of the tax authority, not the company's revenue", "Part of the company's revenue",
  "An expense of the company", "Profit for the company"], 0,
 "Businesses collect VAT and pass it on to HMRC (after deducting VAT they paid on purchases). It's a liability, not income."),
("Financial statements", 1, "Which statement shows a company's position at a single point in time?",
 ["Balance sheet", "Income statement", "Cash flow statement", "Statement of changes in equity"], 0,
 "The balance sheet is a snapshot of assets, liabilities and equity on one date. The other statements cover a period."),
("Accounting equation", 1, "The accounting equation is:",
 ["Assets = liabilities + equity", "Assets = revenue − expenses", "Equity = assets + liabilities", "Profit = assets − liabilities"], 0,
 "Everything a company owns is funded either by what it owes (liabilities) or by its owners (equity). Both sides always balance."),
("Bad debts", 2, "A customer owing £8,000 goes into liquidation and won't pay. No allowance had been made against the debt. What is the effect?",
 ["Receivables fall £8,000 and an £8,000 expense reduces profit", "Revenue is reversed and cash falls £8,000",
  "Cash falls £8,000", "No effect until the liquidation completes"], 0,
 "The receivable is no longer worth anything, so it's written off. That's an expense in the income statement. No cash moves: the money was never received."),
],

# --------------------------------------------------------------------------------------------
"investment_banking": [
("Enterprise value", 1, "Enterprise value represents:",
 ["The value of the whole business to all capital providers", "The value of shareholders' equity only",
  "The company's book value", "The company's annual revenue"], 0,
 "EV is what you'd pay for the whole operating business, ignoring how it's funded. Equity value is just the shareholders' slice."),
("Enterprise value", 2, "Why is cash subtracted when moving from equity value to enterprise value?",
 ["A buyer could use it to pay down debt, reducing the effective price", "Cash is a liability",
  "Cash earns no return", "It is double-counted in revenue"], 0,
 "If you buy a company with £50m in the bank, you effectively get £50m back. So the net cost of the business is lower."),
("Multiples", 2, "Why use EV/EBITDA rather than P/E to compare companies with different debt levels?",
 ["EV/EBITDA is largely unaffected by capital structure", "P/E ignores revenue", "EV/EBITDA includes interest costs", "P/E is always higher"], 0,
 "EBITDA is before interest, and EV includes debt, so both sides are capital-structure neutral. P/E uses net income, which changes with interest costs."),
("Multiples", 2, "Why might a software company trade at a higher EV/EBITDA multiple than a steel producer?",
 ["Higher expected growth and more predictable, recurring revenue", "It always has more debt",
  "It has lower margins", "Steel companies don't report EBITDA"], 0,
 "Investors pay more for each pound of today's earnings when they expect those earnings to grow and to be stable. Cyclical, capital-heavy businesses get lower multiples."),
("DCF", 2, "In a DCF, what does the discount rate represent?",
 ["The return investors require for the risk taken", "The inflation rate", "The company's tax rate", "The growth rate of revenue"], 0,
 "Future cash is worth less than cash today, and riskier cash even less. The discount rate (often WACC) reflects the return investors demand for that risk."),
("DCF", 2, "In a DCF, raising the discount rate will:",
 ["Lower the valuation", "Raise the valuation", "Have no effect", "Only affect the terminal value"], 0,
 "A higher discount rate shrinks the present value of every future cash flow, so the total value falls."),
("DCF", 3, "Terminal value often makes up most of a DCF valuation. Why?",
 ["It captures all cash flows beyond the forecast period", "It is undiscounted",
  "It includes the company's cash balance", "It is calculated with a lower tax rate"], 0,
 "The forecast usually covers 5 to 10 years. Everything after that is in the terminal value, so small changes to its growth or exit multiple move the answer a lot."),
("WACC", 2, "Why is the cost of debt usually lower than the cost of equity?",
 ["Debt holders are paid first and interest is tax-deductible", "Debt has no risk", "Equity holders receive fixed payments", "Banks are cheaper than shareholders"], 0,
 "Lenders rank ahead of shareholders if things go wrong, so they accept a lower return. Interest is also tax-deductible, lowering the cost further."),
("Free cash flow", 2, "Unlevered free cash flow is cash flow:",
 ["Available to all capital providers, before interest", "After interest and debt repayments", "Paid as dividends", "From financing activities"], 0,
 "Unlevered FCF ignores how the company is funded, which is why it's discounted at WACC to get enterprise value."),
("M&A", 1, "A strategic buyer is:",
 ["A company in a related business seeking synergies", "A private equity fund", "A bank lending to the deal", "A hedge fund buying shares"], 0,
 "Strategic buyers are usually operating companies. They can often pay more than financial buyers because they expect cost or revenue synergies."),
("M&A", 2, "A financial sponsor (private equity fund) typically funds an acquisition with:",
 ["A large proportion of debt", "Only its own cash", "Shares in itself", "Government grants"], 0,
 "In a leveraged buyout, debt magnifies the equity return if the business performs. The fund aims to repay debt from the company's cash flows and sell within a few years."),
("M&A", 2, "Which is a cost synergy?",
 ["Closing duplicate head offices after a merger", "Cross-selling products to each other's customers",
  "Raising prices after the deal", "Entering a new country"], 0,
 "Cost synergies come from removing duplication. Revenue synergies, like cross-selling, are less certain and investors usually value them less."),
("Accretion / dilution", 3, "An all-stock acquisition is likely to be accretive to EPS when:",
 ["The target's P/E is lower than the acquirer's", "The target's P/E is higher than the acquirer's",
  "The acquirer pays in cash", "The target has no debt"], 0,
 "If the acquirer's shares are valued more highly (higher P/E), it issues relatively few shares to buy each pound of the target's earnings, so EPS rises."),
("Capital markets", 2, "In an IPO, the bookbuilding process is used to:",
 ["Gauge investor demand and set the price", "Audit the company's accounts", "Write the prospectus", "Choose the stock exchange"], 0,
 "Banks collect orders from investors at different prices. That demand shapes the final offer price and who gets allocated shares."),
("Capital markets", 2, "Why might a company issue a bond rather than new shares?",
 ["Debt is cheaper and doesn't dilute existing shareholders", "Bonds never need to be repaid",
  "Bonds have no interest cost", "Shares are cheaper to issue"], 0,
 "Borrowing keeps ownership with existing shareholders and interest is tax-deductible. The trade-off is fixed payments and higher financial risk."),
("Leverage", 2, "Net debt / EBITDA of 5x suggests:",
 ["High leverage: about five years of EBITDA to repay net debt", "Low leverage", "The company is cash-rich", "A P/E of 5x"], 0,
 "It's a rough measure of how many years of operating earnings it would take to clear net debt. Above 4–5x is usually seen as high."),
("Commercial awareness", 2, "Rising interest rates usually affect M&A activity by:",
 ["Reducing it, because debt-funded deals become more expensive", "Increasing it, because cash earns more",
  "Having no effect", "Only affecting IPOs"], 0,
 "Higher rates raise financing costs and lower valuations, especially hurting leveraged buyouts. Deal volumes tend to slow."),
("Commercial awareness", 2, "A target company's share price jumps 30% on news of a takeover bid. Why?",
 ["Bidders usually pay a premium over the current price", "Shares always rise 30% on news",
  "The company has become more profitable", "The bidder buys shares on the market first"], 0,
 "To persuade shareholders to sell, buyers offer a control premium, often 20–40% above the undisturbed price. The share price moves towards the offer."),
("Valuation", 1, "Which valuation method uses prices paid in past acquisitions of similar companies?",
 ["Precedent transactions", "Trading comparables", "DCF", "Dividend discount model"], 0,
 "Precedent transactions include a control premium, so they usually give higher values than trading comparables."),
("Valuation", 2, "Why do precedent transaction multiples tend to be higher than trading multiples?",
 ["They include a control premium", "They use forecast earnings", "They exclude debt", "They are older"], 0,
 "Buying a whole company gives control over strategy and cash. Buyers pay extra for that, which pushes deal multiples above everyday market multiples."),
("EBITDA", 1, "EBITDA is earnings before:",
 ["Interest, tax, depreciation and amortisation", "Interest, tax, dividends and amortisation",
  "Investment, tax, debt and assets", "Income, tax, depreciation and accruals"], 0,
 "It's a rough proxy for operating cash profit, used because it ignores financing, tax and non-cash charges. It isn't cash flow: it ignores capex and working capital."),
("Pitching", 2, "What is a 'football field' chart used for in a pitch?",
 ["Showing valuation ranges from different methods side by side", "Tracking deal timelines",
  "Comparing league table rankings", "Showing the share price over time"], 0,
 "Each method (comps, precedents, DCF, 52-week range) gets a bar showing its value range. Together they show where a sensible price might sit."),
("Deal process", 2, "In a sell-side auction, the purpose of a non-binding first-round bid is to:",
 ["Narrow the field of buyers before due diligence", "Agree the final price", "Sign the sale contract", "Announce the deal publicly"], 0,
 "First-round bids show who is serious and roughly what they'd pay. The best bidders then get deeper access to information before binding offers."),
("Due diligence", 2, "Due diligence in M&A is mainly about:",
 ["Checking the target's business, finances and risks before committing", "Negotiating the price",
  "Raising debt", "Announcing the deal"], 0,
 "Buyers verify what they're told, covering finances, legal, tax, customers and operations, so there are no expensive surprises after signing."),
("Equity dilution", 2, "A company issues new shares. What happens to existing shareholders who don't buy any?",
 ["Their percentage ownership falls", "Their percentage ownership rises", "They receive cash", "Nothing"], 0,
 "More shares means each existing share is a smaller slice of the company. That's dilution, even if the total value of the company rises."),
],

# --------------------------------------------------------------------------------------------
"asset_management": [
("Diversification", 1, "Diversification reduces:",
 ["Company-specific risk", "Market-wide risk", "All risk", "Inflation"], 0,
 "Spreading money across many holdings means one company's bad news matters less. It can't remove market risk, which hits everything at once."),
("Beta", 2, "A stock with a beta of 1.5 is expected to:",
 ["Move about 1.5 times as much as the market", "Return 1.5% a year", "Be less risky than the market", "Pay a 1.5% dividend"], 0,
 "Beta measures sensitivity to the market. If the market rises 10%, a beta-1.5 stock would be expected to rise about 15%, and fall about 15% if the market falls 10%."),
("Sharpe ratio", 2, "The Sharpe ratio measures:",
 ["Return above the risk-free rate per unit of volatility", "Total return", "Return relative to an index", "Dividend yield"], 0,
 "It asks how much extra return you got for each unit of risk taken. Higher is better when comparing funds."),
("Active vs passive", 1, "A passive fund aims to:",
 ["Track an index at low cost", "Beat the market through stock picking", "Avoid all losses", "Time the market"], 0,
 "Passive funds hold what's in an index and charge low fees. Active funds try to beat the index, and charge more for it."),
("Bonds", 1, "When interest rates rise, existing bond prices usually:",
 ["Fall", "Rise", "Stay the same", "Double"], 0,
 "An existing bond pays a fixed coupon. When new bonds pay more, the old one is less attractive, so its price falls until its yield matches the market."),
("Duration", 2, "A bond with a modified duration of 7 will roughly change in price by how much if yields rise 1 percentage point?",
 ["Fall about 7%", "Rise about 7%", "Fall about 1%", "Fall about 0.7%"], 0,
 "Modified duration is a quick guide to interest rate sensitivity: price change ≈ −modified duration × change in yield. So −7 × 1% ≈ −7%."),
("Asset allocation", 2, "Which typically drives most of the variation in a diversified portfolio's returns?",
 ["Asset allocation between equities, bonds and other assets", "Individual stock selection",
  "Trading frequency", "The fund manager's location"], 0,
 "How much you hold in each asset class matters more for overall returns and risk than which individual securities you pick."),
("Valuation", 2, "A low P/E ratio may indicate:",
 ["The market expects low growth or sees high risk", "The company is definitely undervalued",
  "The company has no debt", "High dividends are guaranteed"], 0,
 "A cheap-looking multiple can be a bargain or a warning. Investors may be pricing in weak growth or problems. Value investors look for cases where the market is too pessimistic."),
("Growth vs value", 1, "A 'value' investing style focuses on:",
 ["Companies that look cheap relative to fundamentals", "Companies with the fastest revenue growth",
  "Only technology stocks", "Bonds rather than shares"], 0,
 "Value investors buy shares trading below what they think they're worth. Growth investors pay up for companies expected to grow quickly."),
("Fees", 2, "Why do fund fees matter so much over the long term?",
 ["They compound, reducing returns every year", "They are only charged once", "They increase returns", "They are tax-deductible for investors"], 0,
 "A 1% annual fee is taken every year from a growing pot, so over decades it can eat a large share of the final value."),
("Inflation", 2, "Which asset is traditionally seen as the most direct protection against inflation?",
 ["Index-linked government bonds", "Long-dated fixed-rate bonds", "Cash in a current account", "Fixed annuities"], 0,
 "Index-linked bonds (linkers) have payments that rise with inflation. Fixed payments lose real value when prices rise."),
("ESG", 2, "ESG integration in investing means:",
 ["Considering environmental, social and governance risks alongside financial analysis",
  "Only investing in charities", "Excluding all oil companies by law", "Guaranteeing higher returns"], 0,
 "It's about factoring material non-financial risks, like carbon regulation or poor governance, into investment decisions. It doesn't guarantee returns."),
("Risk", 2, "Standard deviation of returns is used as a measure of:",
 ["Volatility", "Average return", "Liquidity", "Correlation"], 0,
 "It shows how widely returns swing around their average. Higher standard deviation means a bumpier ride."),
("Correlation", 2, "Adding an asset with low correlation to the rest of a portfolio usually:",
 ["Reduces overall portfolio volatility", "Increases overall volatility", "Has no effect", "Guarantees higher returns"], 0,
 "If assets don't move together, their ups and downs partly cancel out, so the whole portfolio is smoother."),
("Commercial awareness", 2, "Why did many investors move money from equities into bonds when yields rose sharply in 2022–23?",
 ["Bonds offered meaningful income again with less risk", "Equities were banned", "Bonds always beat equities", "Bond prices were rising quickly"], 0,
 "After years of near-zero yields, bonds suddenly paid 4–5%. That made them a real alternative to riskier shares for income-seeking investors."),
("Liquidity", 2, "Why might an open-ended property fund suspend withdrawals?",
 ["Property can't be sold quickly to meet redemptions", "Property prices always rise",
  "Regulators ban withdrawals", "Fees are too high"], 0,
 "Investors can ask for cash daily, but buildings take months to sell. If too many investors want out at once, the fund may have to pause withdrawals."),
("Benchmark", 1, "A fund's benchmark is used to:",
 ["Judge its performance against a relevant index", "Set its fees", "Decide its tax rate", "Guarantee returns"], 0,
 "Comparing to a benchmark shows whether the manager added value or just rode the market."),
("Dividends", 2, "Dividend yield is:",
 ["Annual dividend ÷ share price", "Share price ÷ dividend", "Dividend ÷ earnings", "Dividend growth rate"], 0,
 "It's the income return from holding the share at today's price. A very high yield can signal the market expects a cut."),
],

# --------------------------------------------------------------------------------------------
"markets": [
("Bonds", 1, "Bond prices and yields move:",
 ["In opposite directions", "In the same direction", "Independently", "Only when coupons change"], 0,
 "A bond's cash flows are fixed. Paying less for them means a higher yield, paying more means a lower yield."),
("Yield curve", 2, "An inverted yield curve (short rates above long rates) is often read as a sign of:",
 ["Expected economic slowdown and future rate cuts", "Rising inflation expectations", "Strong growth ahead", "A stock market boom"], 0,
 "Investors accept lower long-term yields when they expect central banks to cut rates in future, usually because growth is weakening."),
("FX", 2, "If the Bank of England raises rates unexpectedly, sterling is most likely to:",
 ["Strengthen", "Weaken", "Stay unchanged", "Be suspended from trading"], 0,
 "Higher rates make sterling deposits and gilts more attractive to international investors, increasing demand for the pound."),
("Options", 2, "A call option gives the holder:",
 ["The right, but not the obligation, to buy at a set price", "The obligation to buy at a set price",
  "The right to sell at a set price", "A guaranteed profit"], 0,
 "The buyer pays a premium for the choice. If the price rises above the strike, they can buy cheaply. If not, they let it expire and lose only the premium."),
("Options", 2, "Which increases the value of a call option, all else equal?",
 ["Higher volatility of the underlying", "Lower share price", "Shorter time to expiry", "Higher strike price"], 0,
 "More volatility means a bigger chance of a large move up, while the downside is capped at the premium. So the option is worth more."),
("Credit", 2, "A widening credit spread on a company's bonds suggests:",
 ["Investors see higher default risk", "The company has become safer", "Government bond yields have fallen", "The bond's coupon has risen"], 0,
 "The spread is the extra yield over government bonds that investors demand for credit risk. If it widens, investors are more worried about getting paid."),
("Market making", 2, "A market maker earns money mainly from:",
 ["The bid-offer spread", "Charging clients a monthly fee", "Predicting long-term trends", "Dividends"], 0,
 "They quote prices to buy (bid) and sell (offer) and earn the gap between them, while managing the risk of positions they take on."),
("Repo", 3, "In a repo transaction, a bank:",
 ["Sells securities and agrees to buy them back later at a set price", "Issues new shares",
  "Lends unsecured to another bank", "Buys a company"], 0,
 "Repo is effectively a short-term secured loan. The securities are collateral, and the difference between sale and repurchase price is the interest."),
("Short selling", 2, "A trader shorts a share at £50 and buys it back at £42. Ignoring costs, the profit per share is:",
 ["£8", "−£8", "£42", "£50"], 0,
 "Shorting means selling borrowed shares first and buying them back later. Selling at £50 and buying at £42 makes £8."),
("Futures", 2, "A key difference between futures and forwards is that futures are:",
 ["Standardised and exchange-traded", "Private and customised", "Always settled in cash", "Free of risk"], 0,
 "Futures trade on exchanges with set contract sizes and daily margining. Forwards are bilateral deals tailored to each party."),
("Hedging", 2, "A UK exporter expecting dollar income in six months is worried the dollar will weaken. Which hedge fits?",
 ["Sell dollars forward", "Buy dollars forward", "Buy UK gilts", "Do nothing"], 0,
 "Agreeing today to sell dollars at a fixed rate locks in the sterling value of the future income, whatever happens to the exchange rate."),
("Commercial awareness", 2, "Higher-than-expected UK inflation data would usually push gilt yields:",
 ["Up", "Down", "Unchanged", "To zero"], 0,
 "Markets expect the central bank to keep rates higher to fight inflation, and investors demand more yield to protect their real return."),
("Commercial awareness", 2, "Why do equity markets often fall when bond yields rise sharply?",
 ["Future profits are discounted at a higher rate and bonds become more competitive", "Companies stop paying dividends",
  "Bond issuance is banned", "Shares and bonds are the same asset"], 0,
 "Higher yields lower the present value of future earnings, hitting growth stocks hardest, and give investors a safer alternative."),
("Swaps", 3, "In a plain vanilla interest rate swap, one party typically:",
 ["Pays fixed and receives floating", "Exchanges shares for bonds", "Swaps currencies only", "Buys an option on a bond"], 0,
 "Companies with floating-rate loans often pay fixed in a swap to lock in their interest cost. No principal changes hands, only the interest difference."),
("Volatility", 2, "The VIX index is often called the 'fear gauge' because it measures:",
 ["Expected volatility implied by S&P 500 option prices", "Trading volumes", "Corporate defaults", "Inflation expectations"], 0,
 "When investors rush to buy protection, option prices rise and so does the VIX. Spikes usually coincide with market stress."),
("Leverage", 2, "A trader buys £100,000 of shares using £20,000 of their own money and £80,000 borrowed. The shares fall 10%. What happens to the trader's equity?",
 ["Falls 50%", "Falls 10%", "Falls 20%", "Falls 8%"], 0,
 "The position loses £10,000, all of it from the trader's £20,000. That's a 50% loss. Leverage magnifies gains and losses."),
],

# --------------------------------------------------------------------------------------------
"commercial_general": [
("Interest rates", 1, "When the Bank of England raises interest rates, borrowing costs for households and businesses usually:",
 ["Rise", "Fall", "Stay the same", "Disappear"], 0,
 "Banks pass higher base rates on through loans and mortgages, especially floating or newly fixed ones. That's how rate rises cool spending and inflation."),
("Inflation", 1, "Inflation means:",
 ["A general rise in prices, reducing what money can buy", "Rising share prices", "Falling unemployment", "A stronger currency"], 0,
 "If prices rise 5% a year and your pay doesn't, you can afford less. The Bank of England's target is 2% CPI inflation."),
("Recession", 1, "A recession is commonly defined as:",
 ["Two consecutive quarters of falling GDP", "A stock market fall of 20%", "Inflation above 5%", "Rising interest rates"], 0,
 "It's a shorthand rule: if the economy shrinks for six months running, it's in a technical recession."),
("Business models", 2, "Why do investors value recurring subscription revenue highly?",
 ["It is predictable and tends to repeat", "It is always more profitable", "It has no costs", "It avoids tax"], 0,
 "If customers pay every month, future revenue is easier to forecast and less risky, so investors pay more for it."),
("Business models", 2, "A supermarket has thin margins but is still profitable. Why?",
 ["High volume and fast stock turnover", "It charges very high prices", "It has no staff costs", "It doesn't pay suppliers"], 0,
 "Making a few pence on each item works when you sell huge volumes and turn stock over quickly."),
("Competition", 2, "What is a company's 'moat'?",
 ["A lasting advantage that protects profits from competitors", "Its cash balance", "Its head office", "Its debt covenants"], 0,
 "Brands, network effects, switching costs or cost advantages can stop rivals eating into profits. Investors pay more for durable moats."),
("Currency", 2, "Sterling weakens against the dollar. Who benefits most?",
 ["A UK company selling heavily in the US", "A UK importer of US goods", "A UK tourist in New York", "A UK firm with dollar debt"], 0,
 "Each dollar earned converts into more pounds. Importers, travellers and firms with dollar costs or debt are worse off."),
("Banking", 2, "How does a commercial bank mainly make money from lending?",
 ["Net interest margin: charging more on loans than it pays on deposits", "Selling shares", "Charging ATM fees only", "Printing money"], 0,
 "The gap between the interest earned on loans and the interest paid to depositors is the bank's core income."),
("Credit risk", 2, "Credit risk is the risk that:",
 ["A borrower fails to repay", "Interest rates change", "A currency moves", "A share price falls"], 0,
 "Lenders charge higher rates to riskier borrowers to compensate for the chance they won't get paid back."),
("Regulation", 2, "Why do banks have to hold capital buffers?",
 ["To absorb losses without failing", "To pay bonuses", "To fund dividends", "To lower their tax"], 0,
 "Capital is the bank's own money, which takes the first losses. Regulators set minimums so banks can survive bad years without taxpayer bailouts."),
("Current affairs", 2, "Why might a company announce a share buyback?",
 ["To return surplus cash and increase earnings per share", "To raise new money", "To reduce its cash because it's illegal to hold", "To pay its staff"], 0,
 "Buying back shares reduces the number in issue, so each remaining share owns more of the profits. It signals management sees the shares as good value or has spare cash."),
("Profitability", 1, "Operating profit is:",
 ["Revenue minus operating costs, before interest and tax", "Revenue minus all costs including tax",
  "Cash in the bank", "Revenue minus cost of sales only"], 0,
 "It shows how much the core business earns before financing and tax, so you can compare companies funded differently."),
],
}
