import assert from 'node:assert/strict';
import { assessAtsReadiness } from '../lib/ats-readiness.mjs';
const base = `Sam Smith sam@example.com\nEducation\nEnglish BA 2024 University\nExperience\nResearch project 2025: analysed literature and presented findings to a seminar group. Developed a structured written report with references and conclusions.\nSkills\nResearch, communication and teamwork. Further academic work and volunteering with a student society.`;
assert.equal(assessAtsReadiness({ cvText: '' }).score, null);
const partial = assessAtsReadiness({ cvText: base });
assert.equal(partial.status, 'partial'); assert.equal(partial.score, null);
const before = assessAtsReadiness({ cvText: base, profile: { targetDivision: 'Investment Banking' } });
assert.equal(before.status, 'assessed'); assert.equal(before.score, 65);
assert.equal(before.weightedContribution.earned, 6.5);
assert.equal(before.weightedContribution.appliedToOverall, false);
const after = assessAtsReadiness({ cvText: base + '\nFinancial modelling and valuation.', profile: { track: 'IBD' } });
assert(after.score > before.score);
assert.deepEqual(after.matchedKeywords, ['valuation', 'financial modelling']);
const repeats = assessAtsReadiness({ cvText: base + ' valuation'.repeat(30), profile: { track: 'IBD' } });
const once = assessAtsReadiness({ cvText: base + ' valuation', profile: { track: 'IBD' } });
assert.equal(repeats.score, once.score);
const explicit = assessAtsReadiness({ cvText: base + ' M&A financial modeling', targetKeywords: ['mergers and acquisitions', 'financial modelling'] });
assert.equal(explicit.score, 100); assert.equal(explicit.keywordSource, 'supplied_target_terms');
const noSubstring = assessAtsReadiness({ cvText: base + ' taxidermy', targetKeywords: ['tax'] });
assert.deepEqual(noSubstring.matchedKeywords, []);
assert(!JSON.stringify(before).includes('sam@example.com'));
console.log('ATS checks passed: incomplete inputs, role terms, aliases, no repetition bonus, privacy and weighting.');